import {
  Info,
  AlertTriangle,
  Sparkles,
  Wind,
  Hand,
  Baby,
  Heart,
  Stethoscope,
  Droplets,
  Users,
  ClipboardCheck,
  Lightbulb,
  Activity,
  Home,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  "סימן מקדים": Sparkles,
  "דגל אדום": AlertTriangle,
  "מה קורה": Activity,
  הורמונים: Heart,
  כלי: Hand,
  טכניקה: Wind,
  מעבר: Home,
  מושגים: Info,
  קריטריון: ClipboardCheck,
  בדרך: Home,
  התקדמות: Activity,
  "שיכוך כאב": Stethoscope,
  תנוחה: Activity,
  התערבות: Stethoscope,
  בדיקה: Stethoscope,
  החלמה: Heart,
  "רגע קסום": Sparkles,
  מגע: Hand,
  הנקה: Baby,
  שגרה: ClipboardCheck,
  החלטה: Info,
  כאב: Activity,
  גוף: Droplets,
  רגש: Heart,
  בית: Home,
  אחים: Users,
  תמיכה: Users,
  "כלל זהב": Lightbulb,
  טיפ: Lightbulb,
  מעקב: ClipboardCheck,
  הלבשה: Baby,
  "לידה חוזרת": Sparkles,
  היערכות: ClipboardCheck,
  לחיצות: Hand,
  הכתרה: Baby,
  התנהגות: Users,
};

export function cardIconFor(tag?: string): LucideIcon {
  return (tag && map[tag]) || Info;
}
